### ISSUE TITLE
Are there any difficulties in implementing the solution in actual scenarios?

### ISSUE THREAD

**Issue by pianogGG** [exiawsh/StreamPETR#10]

**Comment by exiawsh** [comment]
If you want to migrate StreamPETR to a real scene, you may encounter the following difficulties:
1.The memory bank in our code is designed for nuScenes key-frames, and the entry and exit strategies of the memory bank needs to be modified. Because in the real scenarios, the sweep data should be considered. A simple way is that you can save the memory query at a certain spatial ranges, such as 100 meters (instead of a fixed time interval) both in training and testing. Because the time position embedding has poor interpolation and extrapolation performance.

2.The stability of streaming training should be further tested.

3. PETR consumes huge memory due to the global cross attention (object queries with image features), it may hard to conduct on edge devices. But the temporal propagation by object queries can be implemented on other sparse query based single-frame detector (e.g. sparse4d). You can combine the single version of sparse4d with StreamPETR, which also achieve good performance.

**Comment by pianogGG** [comment]
Got it！Thanks.
