### ISSUE TITLE
Architecture Mismatchs between pretrained weights and config files 

### ISSUE THREAD

**Issue by odd2022** [exiawsh/StreamPETR#103]
Hello, 
I would like to use the pretrained version of StreamPETR large, named FCOS3D (model that i found in the table provided in the github page). I followed the tutorial and downloaded the weights fcos3d_vovnet_imgbackbone-remapped.pth.
I would like to test the model on the v1.0-mini version of nuscenes dataset. 

I tried to test the model with typing: tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py ckpts/fcos3d_vovnet_imgbackbone-remapped.pth 1 --eval bbox

and got this message: 

Results writes to test/stream_petr_vov_flash_800_bs2_seq_24e/Mon_Oct__9_14_52_59_2023/pts_bbox/results_nusc.json
Evaluating bboxes of pts_bbox
mAP: 0.0000                                                                                                                                               
mATE: 1.0000
mASE: 1.0000
mAOE: 1.0000
mAVE: 1.0000
mAAE: 1.0000
NDS: 0.0000
Eval time: 0.0s

Per-class results:
Object Class        	AP    	ATE   	ASE   	AOE   	AVE   	AAE   
car                 	0.000 	1.000 	1.000 	1.000 	1.000 	1.000 
truck               	0.000 	1.000 	1.000 	1.000 	1.000 	1.000 
bus                 	0.000 	1.000 	1.000 	1.000 	1.000 	1.000 
trailer             	0.000 	1.000 	1.000 	1.000 	1.000 	1.000 
construction_vehicle	0.000 	1.000 	1.000 	1.000 	1.000 	1.000 
pedestrian          	0.000 	1.000 	1.000 	1.000 	1.000 	1.000 
motorcycle          	0.000 	1.000 	1.000 	1.000 	1.000 	1.000 
bicycle             	0.000 	1.000 	1.000 	1.000 	1.000 	1.000 
traffic_cone        	0.000 	1.000 	1.000 	nan   	nan   	nan   
barrier             	0.000 	1.000 	1.000 	1.000 	nan   	nan   

and above the results, a long message with: 

The model and loaded state dict do not match exactly

unexpected key in source state_dict: bbox_head.cls_convs.0.conv.weight, bbox_head.cls_convs.0.conv.bias, bbox_head.cls_convs.0.gn.weight, bbox_head.cls_convs.0.gn.bias, bbox_head.cls_convs.1.conv.weight, bbox_head.cls_convs.1.conv.bias, bbox_head.cls_convs.1.gn.weight, bbox_head.cls_convs.1.gn.bias, bbox_head.reg_convs.0.conv.weight, bbox_head.reg_convs.0.conv.bias, bbox_head.reg_convs.0.gn.weight, bbox_head.reg_convs.0.gn.bias, bbox_head.reg_convs.1.conv.weight, bbox_head.reg_convs.1.conv.bias ..........

unexpected key in source state_dict: bbox_head.cls_convs.0.conv.weight, bbox_head.cls_convs.0.conv.bias, bbox_head.cls_convs.0.gn.weight, bbox_head.cls_convs.0.gn.bias, bbox_head.cls_convs.1.conv.weight, bbox_head.cls_convs.1.conv.bias, bbox_head.cls_convs.1.gn.weight, bbox_head.cls_convs.1.gn.bias, bbox_head.reg_convs.0.conv.weight, bbox_head.reg_convs.0.conv.bias, bbox_head.reg_convs.0.gn.weight, bbox_head.reg_convs.0.gn.bias, bbox_head.reg_convs.1.conv.weight, bbox_head.reg_convs.1.conv.bias ........

And when I try to launch the command to visualize the results, the detection is not correct at all. I guess this is due to mismatchs between the config file and the weigths but I don't know how to solve the problem.

Do you know how to solve this problem ? Thank you

**Comment by exiawsh** [comment]
StreamPETR don't use the weights fcos3d_vovnet_imgbackbone-remapped.pth. It uses the weights of eva-02. You load the wrong one,

**Comment by odd2022** [comment]
Thank you for answering ! So can I use the weights eva-02 without doing the training part ? 
Or is there no pre-trained model?

**Comment by exiawsh** [comment]
If you want to reproduce StreamPETR Large, please read this https://github.com/exiawsh/StreamPETR/blob/main/docs/ViT_Large.md carefully. If you just want to reproduce the results of V2-99 model on the eval set, using this weight https://github.com/exiawsh/storage/releases/download/v1.0/stream_petr_vov_flash_800_bs2_seq_24e.pth.

**Comment by odd2022** [comment]
> If you want to reproduce StreamPETR Large, please read this https://github.com/exiawsh/StreamPETR/blob/main/docs/ViT_Large.md carefully. If you just want to reproduce the results of V2-99 model on the eval set, using this weight https://github.com/exiawsh/storage/releases/download/v1.0/stream_petr_vov_flash_800_bs2_seq_24e.pth.

Thank you so much it works !

**Comment by odd2022** [comment]
> If you want to reproduce StreamPETR Large, please read this https://github.com/exiawsh/StreamPETR/blob/main/docs/ViT_Large.md carefully. If you just want to reproduce the results of V2-99 model on the eval set, using this weight https://github.com/exiawsh/storage/releases/download/v1.0/stream_petr_vov_flash_800_bs2_seq_24e.pth.

Thank you so much it works !

**Comment by MillionaireChen** [comment]
Thank you so much for your soon reply. It works. After that, I met "TypeError: FormatCode() got an unexpected keyword argument 'verify'" But I installed "pip install yapf==0.40.1" and bypassed it. 

Although it stops because of "AssertionError: Torch not compiled with CUDA enabled", I will try it on a GPU.

Thanks again.


=======================================
projects.mmdet3d_plugin
2024-05-05 22:26:41,916 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: darwin
Python: 3.8.19 (default, Mar 20 2024, 15:00:34) [Clang 14.0.6 ]
CUDA available: False
GCC: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 4.2
  - C++ Version: 201402
  - clang 12.0.0
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode-12.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=OFF, 
。。。。。
