### ISSUE TITLE
Mini-version of Nuscenes Dataset

### ISSUE THREAD

**Issue by SMSajadi99** [exiawsh/StreamPETR#13]
Hello everyone!

Tnx for sharing your helpful project.

I have started working on your Github. However, I want to run the code with mini-version of the Nuscenes dataset. In all part of your code, only the full dataset is used. Since, I have three questions!

1- I want to know that, is it possible to run the code with mini-version? 
2- Also, is it possible to generate the .`pkl `files with `mmdetection`? Or, can you provide it on your Github?
3- Are `sweeps` data (I mean non-annotated frames) necessary for your training algorithm? Or, just by the keyframes we can run the training code.

Thank you.

**Comment by exiawsh** [comment]
Thanks for your interest!
1. Yes, you can run the code with mini-version.
2. You should generate the .pkl files with our provided code on Github, because we merge the 2d annotations into the pkl files, which is a little different from the mmdetection3d. (I will upload the pkl_files of mini-version in a few minutes, please wait).
3. Sweeps data is not used.

**Comment by exiawsh** [comment]
I have uploaded the pkl files of mini-version.
Please check:
https://github.com/exiawsh/storage/releases/download/v1.0/nuscenes2d_temporal_infos_train_mini.pkl
https://github.com/exiawsh/storage/releases/download/v1.0/nuscenes2d_temporal_infos_val_mini.pkl

**Comment by SMSajadi99** [comment]
Thanks for your kind  and quick response.

Sure. 
👌😊
