### ISSUE TITLE
Question about training frames in Table 5 and Table 6 of the paper

### ISSUE THREAD

**Issue by Debrove** [exiawsh/StreamPETR#199]
Hi! I'm very interested in your excellent work.

I have questions about training frames in Table 5 and Table 6 of the paper.
For example, when training frames=8 and Test=V in Table 5, is it mean training frames=batchsize (2) * len_memory (512) // num_propagated (128)? 
In addition to Table 6, when number frames=4, is it indicates number frames=len_memory (512) // num_propagated (128)?

Please point out my mistake if I take a misunderstanding.

Looking forward to your reply~ Thank you~

**Comment by exiawsh** [comment]
Hi,
In table 5, we ablate the training frames,
We have two kinds of training method.
1. The sliding window method, you can set the training frames here:
https://github.com/exiawsh/StreamPETR/blob/2315cf9f077817ec7089c87094ba8a63f76c2acf/projects/configs/StreamPETR/stream_petr_r50_flash_704_bs1_8key_2grad_24e.py#L21
2. The streaming method, 
the training frames = 40 (frames in 1 scene in nusc) // seq_split_num
https://github.com/exiawsh/StreamPETR/blob/2315cf9f077817ec7089c87094ba8a63f76c2acf/projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_90e.py#L215
In table 6, we ablate the length of the memory bank,
number frames for memory bank = len_memory (512) // num_propagated (128)
Please note that the number of frames in the memory bank is not the total length of temporal fusion. Because we use a recurrent approach with latent variables (query features) to propagete temporal information, although the memory bank only has 4 frames, it can be extended to a longer sequence.

**Comment by Debrove** [comment]
Thanks for your quick reply!

Got it!!

SO if I want to reproduce the results in the Table 5 (i.e., the streaming method, training frames=4), I should set seq_split_num=10.

**Comment by Debrove** [comment]
BTW, I want to know in Table 1 of the paper, which setting the results with ResNet-50 are reported on? using streaming setting? or using sliding window?

**Comment by exiawsh** [comment]
Yes. Note, we only provide one way to test. That is, test directly on the entire video (40 frames).

**Comment by exiawsh** [comment]
What we provide in this paper is the sliding window method That's an earlier version. But we switch to streaming method now.

**Comment by Debrove** [comment]
Got it!! Appreciate for quick reply~
