### ISSUE TITLE
About pre-training of ViT-Large

### ISSUE THREAD

**Issue by xiazhongyv** [exiawsh/StreamPETR#56]
Thank you for your amazing work. 

I noticed in your article that: “Following BEVFormerv2,  the ViT-Large is pre-trained on Objects365 and COCO dataset. " But it seems that neither ViT-L nor Objects365 is mentioned on the BEVFormerv2 paper and the BEVFormerv2 nuScenes submission page. Is the pre-training of ViT implemented by your team? Could I find open source pre-training code or pre-trained ViT weights somewhere?

And I have another question. I have noticed that ViT shows much better performance than V2-99. Is this because ViT fits better with the PETR-based model, because ViT has better pre-training, or because ViT is naturally superior to V2-99?

**Comment by exiawsh** [comment]
Sorry, there is a writing typo here. The pretrain is similar to Hop. We found that ViT works better in sparse query-based methods than Bevdets.

**Comment by yingfei1016** [comment]
In BEVFormer v2, although no explicit mention of object365 dataset, the SOTA results for InternImage on the COCO dataset have indeed been pre-trained on object365 dataset. Different from Hop, we not do extra 3D pre-training (such as FCOS3D) or 2D pre-training on NuImages dataset. Pre-trained ViT weights will not be open source in the coming several months.

ViT fits better on PETR-based and other sparse-query methods. For a long time, the large model for sparse-query methods 
 are not work well. We can often see that convnext-base is lower than vov, which  is different from BEVDepth series. However, for ViT backbone, we have tried it on Video-BEV, but only about 2%-3% mAP higher than convnext. 

For this phenomenon, I think that transformer methods will gain more from pre-training. In contrast, BEV method has already 
trained backbone sufficiently, because of the dense supervision and  augmentations.
