### ISSUE TITLE
Confusing about the num_nograd_frames

### ISSUE THREAD

**Issue by Jacky-gsq** [exiawsh/StreamPETR#63]
Hi, I have confuse about the influence of the 'num_nograd_frames', 'num_grad_losses'  in traning, and keep the tensor.detach() in 'stream_petr_head.post_update_memory' as follows:

`_, topk_indexes = torch.topk(rec_score, self.topk_proposals, dim=1) 
  rec_timestamp = topk_gather(rec_timestamp, topk_indexes)
  rec_reference_points = topk_gather(rec_reference_points, topk_indexes).detach()
  rec_memory = topk_gather(rec_memory, topk_indexes).detach()
  rec_ego_pose = topk_gather(rec_ego_pose, topk_indexes)
  rec_velo = topk_gather(rec_velo, topk_indexes).detach()`
 
Could you explain that peleass? Thanks!

**Comment by exiawsh** [comment]
@Jacky-gsq Hi, the 'num_grad_fames' and  'num_frame_losses' is useless when applying stream training. It's used in sliding window training.
The memory tensor needs to be detached when using stream training, because of the RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
If you use sliding window training, the detach operation is not necessary.

**Comment by Jacky-gsq** [comment]
Thanks! Appreciate it!
