### ISSUE TITLE
about the reset memory while training

### ISSUE THREAD

**Issue by fengye1966** [exiawsh/StreamPETR#85]
Thank you for yr excellent work. 

I have one question about the pts_bbox_head.reset_memory() action. Clearly you reset this memory during val process if there's scene change. 
`
if img_metas[0]['scene_token'] != self.prev_scene_token:
    self.prev_scene_token = img_metas[0]['scene_token']
    kwargs['prev_exists'] = kwargs['img_feats'].new_zeros(1)
    self.pts_bbox_head.reset_memory()
else:
    kwargs['prev_exists'] = kwargs['img_feats'].new_ones(1)
`

However, why there's no such action during training process? does it not matter much with the training result? 

Thanks

**Comment by exiawsh** [comment]
@fengye1966 We also consider the memory reset strategy during the training process when the scene changes. However, due to the synchronization issue of multiple batch sizes during the training process, we used another variable (prev_exists) to reset the memory. 
https://github.com/exiawsh/StreamPETR/blob/a732df7aa3d62f5563f07269002a7f3bba16f7af/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L320

**Comment by fengye1966** [comment]
Thank you for your fast response. We got it.
