### ISSUE TITLE
The results became worse when change the length of memory bank and grad_frame

### ISSUE THREAD

**Issue by Jacky-gsq** [exiawsh/StreamPETR#90]
Hi, I found that the mAP became very poor when changed the `queue_length, memory_len, num_frame_losses`. 
Specifically, the mAP is 0.0651 when `queue_length=4, memory_len=1024, num_frame_losses=2`; the mAP is 0.1188 when `queue_length=5, memory_len=768, num_frame_losses=2`; both of that are trained by sliding window and with detech oporeation in `post_update_memory`.
Could you please explain about the effect of the `queue_length, memory_len, num_frame_losses`?  Or is there any some related experiment you have done?

**Comment by exiawsh** [comment]
This seems abnormal. The model doesn't seem to converge. This situation looks more like there are some bugs in the config.
You just need to make sure that (memory_len // topk_proposals)< queue_length.

**Comment by Jacky-gsq** [comment]
Hi, I have checked the config and no setting changed. But the result is abnormal. Could you please help check the evaluation by setting the `queue_length=4, memory_len=1024, num_frame_losses=2` or `queue_length=5, memory_len=768, num_frame_losses=2`?

**Comment by exiawsh** [comment]
@Jacky-gsq I'm sorry, I don't have the bandwidth to replicate this experiment right now. In early versions, this experiment was fine. You can try setting the learning rate of the backbone to 0.1 or using v2-99. I am currently in an idle state due to personal reasons and do not have sufficient resources to replicate the experiment of sliding window training. Once GPUs are available, I will validate these experiments.

**Comment by Jacky-gsq** [comment]
OK, Thanks a lot for your patient explaination and help again! The work is great!
